server:
  port: 8012
spring:
  application:
    name: bank-server
  datasource:
    url: jdbc:mysql://116.62.62.26:3306/bank?useAffectedRows=true
    username: root
    password: 14789632
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java4all.entity


